//
//  DiceViewController.swift
//  com.stonetree.dice
//
//  Created by Victor Rocha de oliveira on 01/12/18.
//  Copyright (c) 2018 Stone Tree. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DiceViewController: UIViewController, DiceDisplayLogic
{
    var router: (NSObjectProtocol & DiceRoutingLogic & DiceDataPassing)?
    
    var presenter: DicePresentationLogic!
    
    @IBOutlet weak var firstDiceView: UIImageView!
    
    @IBOutlet weak var secondDiceView: UIImageView!
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
      super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
      setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
      super.init(coder: aDecoder)
      setup()
    }
    
    private func setup()
    {
        presenter = DicePresenter(self)
        router = DiceRouter(self)
    }
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        presenter.onViewDidLoad()
        presenter.requestCassinoData()
    }
    
    @IBAction func rollButtonListener(_ sender: UIButton) {
      presenter.loadRandomNumbers()
      presenter.loadDiceImages()
    }
    
    func showDiceNumbers(_ firstDice: Dice.ViewModel, _ secondDice: Dice.ViewModel)
    {
      firstDiceView.image = firstDice.image
      secondDiceView.image = secondDice.image
    }

    func updatePolicy(_ rule: String)
    {
        print(rule);
    }
}
