//
//  DicePresenter.swift
//  com.stonetree.dice
//
//  Created by Victor Rocha de oliveira on 01/12/18.
//  Copyright (c) 2018 Stone Tree. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DicePresenter: DicePresentationLogic
{
  
  var viewController: DiceDisplayLogic
    
  var interactor: DiceInteractor!
    
  var model: Dice
    
  init(_ viewController: DiceDisplayLogic){
    self.viewController = viewController
    self.model = Dice()
  }

  func onViewDidLoad()
  {
    self.interactor = DiceInteractor(self)
  }
    
  func loadRandomNumbers() {
    model.firstDice.number = RandomUtils.getRandom(K.MAX_RANDOM_RANGE)
    model.secondDice.number = RandomUtils.getRandom(K.MAX_RANDOM_RANGE)
  }

  func loadDiceImages() {
    model.firstDice.image = UIImage(named: "dice3")
    model.secondDice.image = UIImage(named: "dice4")
    viewController.showDiceNumbers(model.firstDice, model.secondDice)
  }
    
  func requestCassinoData() {
    let request = Dice.Request.init(header: "mCassinoHeader", body: "mCassinoBody")
    interactor.requestCassinoData(request)
  }

  func loadGame(_ response: Dice.Response) {
    viewController.updatePolicy(response.result)
  }
    
}
