//
//  CleanTemplateInteractor.swift
//  com.stonetree.dice
//
//  Created by Victor Rocha de oliveira on 01/12/18.
//  Copyright (c) 2018 Stone Tree. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CleanTemplateBusinessLogic
{
  func doSomething(request: CleanTemplate.Something.Request)
}

protocol CleanTemplateDataStore
{
  //var name: String { get set }
}

class CleanTemplateInteractor: CleanTemplateBusinessLogic, CleanTemplateDataStore
{
  var presenter: CleanTemplatePresentationLogic?
  var worker: CleanTemplateWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CleanTemplate.Something.Request)
  {
    worker = CleanTemplateWorker()
    worker?.doSomeWork()
    
    let response = CleanTemplate.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
