//
//  CleanTemplateRouter.swift
//  com.stonetree.dice
//
//  Created by Victor Rocha de oliveira on 01/12/18.
//  Copyright (c) 2018 Stone Tree. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CleanTemplateRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CleanTemplateDataPassing
{
  var dataStore: CleanTemplateDataStore? { get }
}

class CleanTemplateRouter: NSObject, CleanTemplateRoutingLogic, CleanTemplateDataPassing
{
  weak var viewController: CleanTemplateViewController?
  var dataStore: CleanTemplateDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: CleanTemplateViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: CleanTemplateDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
