//
//  CleanTemplatePresenter.swift
//  com.stonetree.dice
//
//  Created by Victor Rocha de oliveira on 01/12/18.
//  Copyright (c) 2018 Stone Tree. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CleanTemplatePresentationLogic
{
  func presentSomething(response: CleanTemplate.Something.Response)
}

class CleanTemplatePresenter: CleanTemplatePresentationLogic
{
  weak var viewController: CleanTemplateDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CleanTemplate.Something.Response)
  {
    let viewModel = CleanTemplate.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
