//
//  DiceRouter.swift
//  com.stonetree.dice
//
//  Created by Victor Rocha de oliveira on 01/12/18.
//  Copyright (c) 2018 Stone Tree. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DiceRouter: NSObject, DiceRoutingLogic, DiceDataPassing
{
    
  weak var viewController: DiceDisplayLogic?
    
  init(_ viewController: DiceDisplayLogic) {
    self.viewController = viewController
  }
    
  static func goFromTo(_ fromScene: String, _ toScene: String) {
    
  }
    
}
