//
//  DiceModels.swift
//  com.stonetree.dice
//
//  Created by Victor Rocha de oliveira on 01/12/18.
//  Copyright (c) 2018 Stone Tree. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class Dice
{
    
    var firstDice = ViewModel()
    var secondDice = ViewModel()
    
    struct Request
    {
        var header: String
        var body: String
    }
    
    struct Response
    {
        var result: String
    }
    
    struct ViewModel
    {
        var number: Int?
        var image: UIImage?
    }
    
    struct Error
    {
        var code: Int
        var message: String
    }

}
