//
//  DiceInteractor.swift
//  com.stonetree.dice
//
//  Created by Victor Rocha de oliveira on 01/12/18.
//  Copyright (c) 2018 Stone Tree. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DiceInteractor: DiceBusinessLogic, DiceDataStore
{
    
  var presenter: DicePresentationLogic
  var worker: DiceWorker

  init(_ presenter: DicePresentationLogic)
  {
    self.presenter = presenter
    self.worker = DiceWorker()
  }
  
  func requestCassinoData(_ request: Dice.Request)
  {
    worker.requestGameRule()
    
    let response = Dice.Response.init(result: "I came back from Async Task")
    presenter.loadGame(response)
  }
}
